version: '3'

services:

    livraria_database:
        image: mysql:8.0
        restart: always
        ports:
            - 3306:3306
        env_file:
            - livraria_database.env
            
    livraria_app:
        build: .
        restart: always
        ports:
            - 8080:8080
        env_file:
            - livraria_app.env